name: Deploy to cloudtype
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v2
        with:
          node-version: '16'
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v2
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: rbghks19/employee_management
          stage: main
          yaml: |
            name: employee-management-system
            app: java@17
            options:
              ports: 8080
              env:
                - name: DB_HOST
                  value: svc.sel5.cloudtype.app
                - name: DB_PORT
                  value: "31067"
                - name: DB_NAME
                  value: employee_management
                - name: DB_ID
                  value: root
                - name: DB_PASSWORD
                  value: Password!
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
